# Generated by Django 3.2.7 on 2022-01-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodemcu0', '0002_alter_auditrecord_last_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditrecord',
            old_name='last_timestamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='data',
            field=models.CharField(default='nULwQOYxfZDTVNisyghMuIzHFtSdWkElovqmaejApPRKCJBbrG', max_length=50),
        ),
    ]
