# Generated by Django 3.2.5 on 2022-01-29 06:22

from django.db import migrations, models
import nodemcu0.models


class Migration(migrations.Migration):

    dependencies = [
        ('nodemcu0', '0003_auto_20220105_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='data',
            field=models.CharField(default=nodemcu0.models.AuditRecord.random_char, max_length=50),
        ),
    ]
